### Kõigi sõnumite lugemine
GET http://localhost:3030/api/sonumid HTTP/1.1

### Sõnumi saatmine
POST http://localhost:3030/api/sonumid HTTP/1.1
Content-Type: application/json

{
    "nimi": "Kalle",
    "sonum": "Veel üks sõnum"
}


### Kõigi matkade lugemine
GET http://localhost:3030/api/matkad HTTP/1.1

### Matka lisamine
POST http://localhost:3030/api/matkad HTTP/1.1
Content-Type: application/json

{
    "nimetus": "Matk Kilingi-Nõmmel",
    "pildiUrl": "/assets/Hiker.png",
    "kirjeldus": "20km puhast elamust.",
    "osalejad": ["malle@mail.ee", "toomas@hot.ee"]
}


### Kõigi uudiste lugemine
GET http://localhost:3030/api/uudised HTTP/1.1

### Uudiste eemaldamine
DELETE http://localhost:3030/api/uudis/2 HTTP/1.1


### Matka lisamine
POST http://localhost:3030/api/matk HTTP/1.1
Content-Type: application/json

{
    "nimetus": "Matk Kuutsemäel",
    "pildiUrl": "/assets/Hiker.png",
    "kirjeldus": "10km kiiret jooksu.",
    "osalejad": ["malle@mail.ee", "toomas@hot.ee"]
}


### Osaleja lisamine matkale
PATCH http://localhost:3030/api/matk/1/osaleja
Content-Type: application/json

{
    "email": "uus.matkaja@test.ee"
}

### Osaleja eemaldamine matkalt
DELETE http://localhost:3030/api/matk/1/osaleja/2

